### PR TITLE
Add conversion for TB, PB, EB, ZB and YB

### PR DESCRIPTION
**Pull request by RamonHossein**
Add Conversion for:
    \* Terabyte
    \* Petabyte
    \* Exabyte
    \* Zettabyte
    \* Yottabyte

### CODE REVIEW

**Comment by plribeiro3000** [comment]
hello @RamonHossein. Thank you for your contribution!

Could you take a look at the broken tests?

**Comment by RamonHossein** [comment]
I'm with problem with old versions (Ruby 1.9.2). Do you know how I set an answer for each type of version?

**Comment by plribeiro3000** [comment]
@RamonHossein I think thats a round issue between multiple ruby implementations. It might be better, easier to just increase the size of the test number a few.

**Comment by RamonHossein** [comment]
@plribeiro3000 resolved the broken tests.

**Comment by plribeiro3000** [comment]
Awesome @RamonHossein !

Could you squash your commits into one?

Thanks!

**Comment by plribeiro3000** [comment]
Thank you @RamonHossein !

**Comment by plribeiro3000** [comment]
Released as `v2.2.0`.

**Pull request merged**
